name: Push Action

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multiline script
      run: |
        ls -altG
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
